# Generated Makefile -- DO NOT EDIT!

CC=C:/Users/tmiller/MagicLeap/mlsdk/v0.24.1/tools/toolchains/bin/aarch64-linux-android-clang
COMPILER_PREFIX=
CXX=C:/Users/tmiller/MagicLeap/mlsdk/v0.24.1/tools/toolchains/bin/aarch64-linux-android-clang++
HOST=win64
LINKER_PREFIX=
MLSDK=C:/Users/tmiller/MagicLeap/mlsdk/v0.24.1
OBJCOPY=C:/Users/tmiller/MagicLeap/mlsdk/v0.24.1/tools/toolchains/bin/aarch64-linux-android-objcopy.exe
RM=rm
SPEC=debug_lumin_clang-3.8_aarch64
STRIP=C:/Users/tmiller/MagicLeap/mlsdk/v0.24.1/tools/toolchains/bin/aarch64-linux-android-strip.exe
WebRTCPlugin_BASE=D:/Dev/GitProjects/com.unity.webrtc/Plugin~/WebRTCPlugin
WebRTCPlugin_CPPFLAGS=-I$(WebRTCPlugin_BASE)/. -I$(WebRTCPlugin_BASE)/../unity/include -I$(MLSDK)/lumin/stl/libc++-lumin/include -I$(MLSDK)/include/runtime/external/webrtc -I$(MLSDK)/include/runtime/external/webrtc/third_party/abseil-cpp -I$(MLSDK)/include -I$(MLSDK)/include/runtime/external/PocoJSON -I$(MLSDK)/include/runtime/external/PocoFoundation -I$(MLSDK)/include/runtime/external/PocoNetSSL_OpenSSL -I$(MLSDK)/include/runtime/external/PocoNet -I$(MLSDK)/include/runtime/external/openssl -I$(MLSDK)/include/runtime/external/PocoCrypto -I$(MLSDK)/include/runtime/external/PocoUtil -I$(MLSDK)/include/runtime/external/PocoXML -DML_DEFAULT_LOG_TAG=\"WEBRTC\" -DLOG_TAG=\"WEBRTC\" -DPOCO_STATIC -DWEBRTC_ANDROID=1 -DWEBRTC_LINUX=1 -DWEBRTC_NOVA=1 -DWEBRTC_POSIX=1 -DUNITY_LUMIN=1 -DLUMIN=1 -D_DEBUG=1 -DSUPPORT_OPENGL_CORE=1
WebRTCPlugin_CXXFLAGS=--sysroot=$(MLSDK)/lumin -march=armv8-a -mcpu=cortex-a57+crypto -fPIC -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -g -fno-limit-debug-info -O0 -frtti -std=c++1z
WebRTCPlugin_LDFLAGS=-Wl,-unresolved-symbols=ignore-in-shared-libs --sysroot=$(MLSDK)/lumin -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--build-id -no-canonical-prefixes -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--enable-new-dtags '-Wl,-rpath=$$ORIGIN' -g -fvisibility=hidden
WebRTCPlugin_LIBS=-L$(MLSDK)/lumin/stl/libc++-lumin/lib -L$(MLSDK)/lib/lumin -Wl,--start-group -Bstatic -Wl,--no-as-needed -lwebrtc_debug -lPocoJSON -lPocoFoundation -lPocoNetSSL -lPocoNet -lPocoCrypto -lcrypto -lssl -lPocoUtil -lPocoXML -Bdynamic -lc -lml_ext_logging -lml_lifecycle -lml_perception_client -lc++ -llog -lEGL -lGLESv2 -lGLESv3 -lm -Wl,--end-group
WebRTCPlugin_OUTPUT=$(WebRTCPlugin_BASE)/.out/$(SPEC)

$(WebRTCPlugin_OUTPUT)/libWebRTCPlugin.so : $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Context.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DataChannelObject.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyAudioDevice.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyVideoEncoder.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Logger.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/NvVideoCapturer.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/MediaStreamObserver.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/PeerConnectionObject.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/SetSessionDescriptionObserver.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityRenderEvent.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityVideoEncoderFactory.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCapturer.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCaptureTrackSource.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/WebRTCPlugin.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/EncoderFactory.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/IGraphicsDevice.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/ITexture2D.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp.o $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Linking\ shared\ object\ 'libWebRTCPlugin.so'...
	$(ECHO) cd $(WebRTCPlugin_OUTPUT) && $(LINKER_PREFIX) $(CC) -o libWebRTCPlugin.so -shared obj.WebRTCPlugin/Context.cpp.o obj.WebRTCPlugin/DataChannelObject.cpp.o obj.WebRTCPlugin/DummyAudioDevice.cpp.o obj.WebRTCPlugin/DummyVideoEncoder.cpp.o obj.WebRTCPlugin/Logger.cpp.o obj.WebRTCPlugin/NvVideoCapturer.cpp.o obj.WebRTCPlugin/MediaStreamObserver.cpp.o obj.WebRTCPlugin/PeerConnectionObject.cpp.o obj.WebRTCPlugin/SetSessionDescriptionObserver.cpp.o obj.WebRTCPlugin/UnityRenderEvent.cpp.o obj.WebRTCPlugin/UnityVideoEncoderFactory.cpp.o obj.WebRTCPlugin/VideoCapturer.cpp.o obj.WebRTCPlugin/VideoCaptureTrackSource.cpp.o obj.WebRTCPlugin/WebRTCPlugin.cpp.o obj.WebRTCPlugin/Codec/EncoderFactory.cpp.o obj.WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp.o obj.WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp.o obj.WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp.o obj.WebRTCPlugin/GraphicsDevice/IGraphicsDevice.cpp.o obj.WebRTCPlugin/GraphicsDevice/ITexture2D.cpp.o obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp.o obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp.o $(WebRTCPlugin_LIBS) $(WebRTCPlugin_LDFLAGS)
	$(ECHO) $(OBJCOPY) --only-keep-debug $(WebRTCPlugin_OUTPUT)/libWebRTCPlugin.so $(WebRTCPlugin_OUTPUT)/libWebRTCPlugin.sym
	$(ECHO) $(OBJCOPY) --add-gnu-debuglink $(WebRTCPlugin_OUTPUT)/libWebRTCPlugin.sym $(WebRTCPlugin_OUTPUT)/libWebRTCPlugin.so $(WebRTCPlugin_OUTPUT)/libWebRTCPlugin.so
	$(ECHO) $(STRIP) --strip-unneeded $(WebRTCPlugin_OUTPUT)/libWebRTCPlugin.so

$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Context.cpp.o : $(WebRTCPlugin_BASE)/Context.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'Context.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/Context.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Context.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Context.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/Context.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Context.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Context.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DataChannelObject.cpp.o : $(WebRTCPlugin_BASE)/DataChannelObject.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'DataChannelObject.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/DataChannelObject.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DataChannelObject.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DataChannelObject.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/DataChannelObject.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DataChannelObject.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DataChannelObject.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyAudioDevice.cpp.o : $(WebRTCPlugin_BASE)/DummyAudioDevice.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'DummyAudioDevice.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/DummyAudioDevice.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyAudioDevice.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyAudioDevice.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/DummyAudioDevice.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyAudioDevice.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyAudioDevice.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyVideoEncoder.cpp.o : $(WebRTCPlugin_BASE)/DummyVideoEncoder.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'DummyVideoEncoder.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/DummyVideoEncoder.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyVideoEncoder.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyVideoEncoder.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/DummyVideoEncoder.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyVideoEncoder.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyVideoEncoder.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Logger.cpp.o : $(WebRTCPlugin_BASE)/Logger.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'Logger.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/Logger.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Logger.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Logger.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/Logger.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Logger.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Logger.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/NvVideoCapturer.cpp.o : $(WebRTCPlugin_BASE)/NvVideoCapturer.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'NvVideoCapturer.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/NvVideoCapturer.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/NvVideoCapturer.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/NvVideoCapturer.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/NvVideoCapturer.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/NvVideoCapturer.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/NvVideoCapturer.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/MediaStreamObserver.cpp.o : $(WebRTCPlugin_BASE)/MediaStreamObserver.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'MediaStreamObserver.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/MediaStreamObserver.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/MediaStreamObserver.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/MediaStreamObserver.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/MediaStreamObserver.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/MediaStreamObserver.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/MediaStreamObserver.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/PeerConnectionObject.cpp.o : $(WebRTCPlugin_BASE)/PeerConnectionObject.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'PeerConnectionObject.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/PeerConnectionObject.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/PeerConnectionObject.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/PeerConnectionObject.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/PeerConnectionObject.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/PeerConnectionObject.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/PeerConnectionObject.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/SetSessionDescriptionObserver.cpp.o : $(WebRTCPlugin_BASE)/SetSessionDescriptionObserver.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'SetSessionDescriptionObserver.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/SetSessionDescriptionObserver.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/SetSessionDescriptionObserver.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/SetSessionDescriptionObserver.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/SetSessionDescriptionObserver.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/SetSessionDescriptionObserver.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/SetSessionDescriptionObserver.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityRenderEvent.cpp.o : $(WebRTCPlugin_BASE)/UnityRenderEvent.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'UnityRenderEvent.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/UnityRenderEvent.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityRenderEvent.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityRenderEvent.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/UnityRenderEvent.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityRenderEvent.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityRenderEvent.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityVideoEncoderFactory.cpp.o : $(WebRTCPlugin_BASE)/UnityVideoEncoderFactory.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'UnityVideoEncoderFactory.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/UnityVideoEncoderFactory.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityVideoEncoderFactory.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityVideoEncoderFactory.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/UnityVideoEncoderFactory.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityVideoEncoderFactory.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityVideoEncoderFactory.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCapturer.cpp.o : $(WebRTCPlugin_BASE)/VideoCapturer.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'VideoCapturer.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/VideoCapturer.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCapturer.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCapturer.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/VideoCapturer.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCapturer.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCapturer.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCaptureTrackSource.cpp.o : $(WebRTCPlugin_BASE)/VideoCaptureTrackSource.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'VideoCaptureTrackSource.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/VideoCaptureTrackSource.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCaptureTrackSource.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCaptureTrackSource.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/VideoCaptureTrackSource.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCaptureTrackSource.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCaptureTrackSource.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/WebRTCPlugin.cpp.o : $(WebRTCPlugin_BASE)/WebRTCPlugin.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'WebRTCPlugin.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/WebRTCPlugin.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/WebRTCPlugin.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/WebRTCPlugin.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/WebRTCPlugin.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/WebRTCPlugin.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/WebRTCPlugin.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/EncoderFactory.cpp.o : $(WebRTCPlugin_BASE)/Codec/EncoderFactory.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'EncoderFactory.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/Codec/EncoderFactory.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/EncoderFactory.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/EncoderFactory.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/Codec/EncoderFactory.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/EncoderFactory.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/EncoderFactory.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp.o : $(WebRTCPlugin_BASE)/Codec/SoftwareCodec/SoftwareEncoder.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'SoftwareEncoder.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/Codec/SoftwareCodec/SoftwareEncoder.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/Codec/SoftwareCodec/SoftwareEncoder.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp.o : $(WebRTCPlugin_BASE)/GraphicsDevice/GraphicsDevice.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'GraphicsDevice.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/GraphicsDevice/GraphicsDevice.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/GraphicsDevice/GraphicsDevice.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp.o : $(WebRTCPlugin_BASE)/GraphicsDevice/GraphicsUtility.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'GraphicsUtility.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/GraphicsDevice/GraphicsUtility.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/GraphicsDevice/GraphicsUtility.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/IGraphicsDevice.cpp.o : $(WebRTCPlugin_BASE)/GraphicsDevice/IGraphicsDevice.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'IGraphicsDevice.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/GraphicsDevice/IGraphicsDevice.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/IGraphicsDevice.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/IGraphicsDevice.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/GraphicsDevice/IGraphicsDevice.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/IGraphicsDevice.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/IGraphicsDevice.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/ITexture2D.cpp.o : $(WebRTCPlugin_BASE)/GraphicsDevice/ITexture2D.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'ITexture2D.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/GraphicsDevice/ITexture2D.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/ITexture2D.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/ITexture2D.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/GraphicsDevice/ITexture2D.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/ITexture2D.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/ITexture2D.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp.o : $(WebRTCPlugin_BASE)/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'OpenGLGraphicsDevice.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp.d
$(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp.o : $(WebRTCPlugin_BASE)/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp $(WebRTCPlugin_BASE)/WebRTCPlugin.mabu $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/.metadata/components/poco_crypto.comp $(MLSDK)/.metadata/components/poco_foundation.comp $(MLSDK)/.metadata/components/poco_json.comp $(MLSDK)/.metadata/components/poco_net.comp $(MLSDK)/.metadata/components/poco_netssl.comp $(MLSDK)/.metadata/components/poco_util.comp $(MLSDK)/.metadata/components/poco_xml.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/standard-c++/17.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[WebRTCPlugin\]\ Compiling\ 'OpenGLTexture2D.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(WebRTCPlugin_BASE)/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp -o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp.o -MD -MP -MF $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp.d $(WebRTCPlugin_CPPFLAGS) $(WebRTCPlugin_CXXFLAGS)
	$(ECHO) echo $(WebRTCPlugin_BASE)/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp : >> $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp.d

-include $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp.d

WebRTCPlugin-clean :: 
	$(INFO) Cleaning\ WebRTCPlugin...
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/libWebRTCPlugin.so $(WebRTCPlugin_OUTPUT)/WebRTCPlugin.sym $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Context.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Context.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DataChannelObject.cpp.o
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DataChannelObject.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyAudioDevice.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyAudioDevice.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyVideoEncoder.cpp.o
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/DummyVideoEncoder.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Logger.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Logger.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/NvVideoCapturer.cpp.o
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/NvVideoCapturer.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/MediaStreamObserver.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/MediaStreamObserver.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/PeerConnectionObject.cpp.o
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/PeerConnectionObject.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/SetSessionDescriptionObserver.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/SetSessionDescriptionObserver.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityRenderEvent.cpp.o
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityRenderEvent.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityVideoEncoderFactory.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/UnityVideoEncoderFactory.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCapturer.cpp.o
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCapturer.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCaptureTrackSource.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/VideoCaptureTrackSource.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/WebRTCPlugin.cpp.o
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/WebRTCPlugin.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/EncoderFactory.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/EncoderFactory.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp.o
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp.o
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/IGraphicsDevice.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/IGraphicsDevice.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/ITexture2D.cpp.o
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/ITexture2D.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp.o $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp.d $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp.o
	$(ECHO) $(RM) -rf $(WebRTCPlugin_OUTPUT)/obj.WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp.d

WebRTCPlugin-all :: -make-directories $(WebRTCPlugin_OUTPUT)/libWebRTCPlugin.so

